version: '3.7'

services:
  event-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5004:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@event-db:5432/event_dev
      - DATABASE_TESTING_URL=postgresql://postgres:postgres@event-db:5432/event_dev
      - TWILIO_AUTH_TOKEN=b9255c1b474b0de9843f45378375ad0e
      - TWILIO_ACCOUNT_SID=ACf84089dffba0280beaaf81e4fa7d2944
      - SERVICE_INSTANCE_SID=IS25d18fb4ea71fd1fa9043e4013993a26
      - SENDER_PHONE_NUMBER=+18478659454
      - RECEIVER_PHONE_NUMBER=+919826376555
    depends_on:
      - event-db

  event-db:
    build:
      context: ./app/database
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

